Document: liblmdb
Title: Debian liblmdb Manual
Author: <insert document author here>
Abstract: This manual describes what liblmdb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/liblmdb/liblmdb.sgml.gz

Format: postscript
Files: /usr/share/doc/liblmdb/liblmdb.ps.gz

Format: text
Files: /usr/share/doc/liblmdb/liblmdb.text.gz

Format: HTML
Index: /usr/share/doc/liblmdb/html/index.html
Files: /usr/share/doc/liblmdb/html/*.html
